# -*- coding: utf-8 -*-
"""1.3.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1GX6nfgBaaHvF9nQZL6XoraoYmgSWog4e
"""

from IPython.display import Audio
import numpy as np
import matplotlib.pyplot as plt
import scipy.io.wavfile
Audio('task.wav')

fs, x = scipy.io.wavfile.read('task.wav')
print(fs)
print(x)

print(x.dtype)

x.size

x1=x[8000:10000]                
k=np.arange(x1.size)            

plt.figure(figsize=[19, 4])       
plt.plot(k/fs, x1, 'b.')           
plt.grid()                             
plt.xlabel("$t$, c")                      
plt.ylabel("$x[k]$")             
plt.tight_layout()