# -*- coding: utf-8 -*-
"""1.3.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1GX6nfgBaaHvF9nQZL6XoraoYmgSWog4e
"""

import numpy as np              
import matplotlib.pyplot as plt

N=12                                                           
k=np.arange(-2, 10, 1)    
x=np.zeros(N)
x[9]=1        
num_levels=50                  

plt.figure(figsize=[10, 4])     
plt.stem(k, x, 'b', 'bo', label='дискретизованный сигнал $x[k-7]$')                                                   

plt.xlabel("$t$, c")                    
plt.ylabel("x[k-7]$")              
plt.title("Аналоговый и дискретизованный сигналы") 
plt.legend(loc='best', bbox_to_anchor=(1, 1))
plt.tight_layout()

k=np.arange(-5, 5, 0.2)                       
x=np.sin(2*np.pi*1/4*k)      
num_levels=50                  

plt.figure(figsize=[12, 4])     
t=np.linspace(0, N, num=10)        
                                   
plt.stem(k, x, 'b', 'bo', label='дискретизованный сигнал $sin(2*pi*1/4*k)$')                                               
plt.grid()                              
plt.xlabel("$t$, c")                    
plt.ylabel("x[k]$")              
plt.title("Аналоговый и дискретизованный сигналы") 
plt.legend(loc='best', bbox_to_anchor=(1, 1))
plt.tight_layout()

N=12                                                           
k=np.arange(-2, 10, 1)    
x=np.zeros(N)
x[3]=1       
x[4]=1        
x[5]=1        
x[2]=1        

num_levels=50                  

plt.figure(figsize=[10, 4])     
plt.stem(k, x, 'b', 'bo', label='дискретизованный сигнал $sum(m=0, 4)(1[k-m]$')                                                   

plt.xlabel("$t$, c")                    
plt.ylabel("x[k-7]$")              
plt.title("Аналоговый и дискретизованный сигналы") 
plt.legend(loc='best', bbox_to_anchor=(1, 1))
plt.tight_layout()

k=np.arange(-2, 10, 1)                       
x=np.power(-0.5, k)
x[0] = 0
x[1] = 0
num_levels=50                  

plt.figure(figsize=[12, 4])     
t=np.linspace(0, N, num=10)        
                                   
plt.stem(k, x, 'b', 'bo', label='дискретизованный сигнал $sin(2*pi*1/4*k)$')                                               
plt.grid()                              
plt.xlabel("$t$, c")                    
plt.ylabel("x[k]$")              
plt.title("Аналоговый и дискретизованный сигналы") 
plt.legend(loc='best', bbox_to_anchor=(1, 1))
plt.tight_layout()