# -*- coding: utf-8 -*-
"""Untitled2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/17SoCr71eW5ImGZK_ngpxTxpwAYDnF_TH
"""

from IPython.display import Audio
import numpy as np
import matplotlib.pyplot as plt
import scipy.io.wavfile
Audio('tuning-fork.wav')

fs, x = scipy.io.wavfile.read('tuning-fork.wav')
print(fs)
print(x)

print(x.dtype)

x.size

x.dtype.num

x1=x[8000:10000]                
k=np.arange(x1.size)            

plt.figure(figsize=[16, 4])       
plt.plot(k/fs, x1, 'b.')           
plt.grid()                             
plt.xlabel("$t$, c")                      
plt.ylabel("$x[k]$")             
plt.tight_layout()