# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1i1zIhm2cIU2kKIvx6-7IU7k9jPMh3tqM
"""

# Вариант 5

import numpy as np
import matplotlib.pyplot as plt

a = np.array([1, 3, 5, 7, 9])
b = np.arange(1, 10, 2)
c = np.linspace(1, 9, 5, dtype=int)
print(a)
print(b)
print(c)

import numpy as np
import matplotlib.pyplot as plt

d = np.arange(1, 101)
print(d)

qq = 0.07
x = np.arange(1, 101, dtype=float)
for i in d:
    x[i-1] = np.sin(2 * np.pi * qq * d[i-1])
print(x)


plt.figure(figsize=[12, 5], dpi=100)
plt.plot(d, x, linestyle = '--', color = 'crimson')
plt.stem(d, x, use_line_collection=True)
plt.xlabel("$x$")
plt.ylabel("$x(d)$")
plt.xticks(ticks=np.arange(x.size))
plt.title("График x(t)")
plt.grid()
plt.show()

import numpy as np
import matplotlib.pyplot as plt

d = np.arange(1, 101)
print(d)

qq = 0.07

def y(x):
  if x == 0:
    return 1
  else:
    return np.sin(x)/x

t = np.arange(1, 101, dtype=float)
for i in d:
  t[i-1] = y(d[i-1])


plt.figure(figsize=[12, 5], dpi=100)
plt.plot(d, t, linestyle = '--', color = 'crimson')
plt.stem(d, t, use_line_collection=True)
plt.xlabel("$x$")
plt.ylabel("$y(x)$")
plt.xticks(ticks=np.arange(t.size))
plt.title("График y(x)")
plt.grid()
plt.show()

import numpy as np
import matplotlib.pyplot as plt

d = np.arange(1, 101)
print(d)

qq = 0.07

z = np.arange(1, 101, dtype=complex)
for i in d:
  z[i-1] = np.exp(-1j * 2 * np.pi * qq * d[i-1])
print(z)

plt.figure(figsize=[12, 5], dpi=100)
plt.plot(d, z.real, '-')
plt.xlabel("$x$")
plt.ylabel("$z.real(x)$")
plt.xticks(ticks=np.arange(d.size))
plt.title("График z.real(x)")
plt.grid()
plt.show()

plt.figure(figsize=[12, 5], dpi=100)
plt.plot(d, z.imag, linestyle = '-')
plt.xlabel("$x$")
plt.ylabel("$z.imag(x)$")
plt.xticks(ticks=np.arange(x.size))
plt.title("График z.imag(x)")
plt.grid()
plt.show()